# Generated by Django 4.1.5 on 2023-02-24 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sustainable_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=400)),
                ('type', models.CharField(choices=[('minigame', 'Minigame'), ('location', 'Location'), ('poll', 'Poll'), ('personal', 'Personal')], max_length=8)),
                ('point_reward', models.IntegerField(default=0)),
                ('xp_reward', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('on_sale', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='equipped_items',
            field=models.ManyToManyField(related_name='equipped_by', to='sustainable_app.item'),
        ),
        migrations.AddField(
            model_name='user',
            name='owned_items',
            field=models.ManyToManyField(related_name='owned_by', to='sustainable_app.item'),
        ),
        migrations.AddField(
            model_name='item',
            name='unlock_level',
            field=models.IntegerField(default=0),
        ),
    ]
