# Generated by Django 4.1.5 on 2023-03-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sustainable_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='survey_text',
            field=models.CharField(default='hello', max_length=200),
            preserve_default=False,
        ),
    ]
