# Generated by Django 4.1.5 on 2023-03-14 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sustainable_app', '0002_survey_survey_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='currentlyActive',
            field=models.BooleanField(default=False),
        ),
    ]
