# Generated by Django 4.1.7 on 2023-03-05 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sustainable_app', '0002_goal_item_user_equipped_items_user_owned_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='game_keeper',
            field=models.BooleanField(default=False),
        ),
    ]
