# Generated by Django 4.1.5 on 2023-02-24 11:20

from django.db import migrations

items = [
    (
        "character",
        [
            ("cat", 0, True),
            ("fish", 200, True),
            ("frog", 400, True),
            ("bird", 600, True),
            ("badger", 800, True),
        ],
    ),
    (
        "accessory",
        [
            ("none", 0, False),
            ("viking", 100, True),
            ("party", 400, True),
            ("crown", 600, True),
        ],
    ),
    (
        "username_color",
        [
            ("u_black", 200, True),
            ("u_green", 200, True),
            ("u_purple", 200, True),
            ("u_orange", 200, True),
            ("u_blue", 200, True),
        ],
    ),
    (
        "background_color",
        [
            ("b_white", 200, True),
            ("b_blue", 200, True),
            ("b_pink", 200, True),
            ("b_grey", 200, True),
            ("b_green", 200, True),
        ],
    ),
]


def make_items(apps, schema_editor):
    Item = apps.get_model('sustainable_app', 'Item')

    # Add all items to database
    for (type, values) in items:
        for [name, cost, on_sale] in values:
            item = Item(type=type, name=name, cost=cost, on_sale=on_sale)
            item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('sustainable_app', '0002_goal_item_user_equipped_items_user_owned_items'),
    ]

    operations = [
        migrations.RunPython(make_items)
    ]
