# Generated by Django 4.1.5 on 2023-03-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sustainable_app', '0003_create_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('a1', models.CharField(max_length=255)),
                ('a2', models.CharField(max_length=255)),
                ('a3', models.CharField(max_length=255)),
                ('a4', models.CharField(max_length=255)),
                ('correct_answer', models.IntegerField(choices=[(1, 'a1'), (2, 'a2'), (3, 'a3'), (4, 'a4')])),
            ],
        ),
    ]
