# Generated by Django 4.1.5 on 2023-02-24 11:20

from django.db import migrations

def make_game_keeper(apps, schema_editor):
    """
    Creates a gamekeeper called root for admin use
    """
    User = apps.get_model('sustainable_app', 'User')
    
    user = User.objects.create_user("root", "root@example.com", "admin")
    user.first_name = "root"
    user.last_name = "root"
    user.game_keeper = True
    user.save()

def undo_make_game_keeper(apps, schema_editor):
    """
    Reverse function for undoing migration, deletes root user
    """
    User = apps.get_model('sustainable_app', 'User')
    try:
        user = User.objects.get(username="root")
        user.delete()
    except User.DoesNotExist:
        pass



class Migration(migrations.Migration):

    dependencies = [
        ('sustainable_app', '0003_user_game_keeper'),
    ]

    operations = [
        migrations.RunPython(make_game_keeper, undo_make_game_keeper)
    ]
