# Generated by Django 4.1.7 on 2023-03-09 16:58

from django.db import migrations, models

import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sustainable_app', '0004_create_game_keeper'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sustainable_app.goal')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('recycle', 'Recycling Bin'), ('water', 'Water Fountain')], max_length=7)),
                ('clue', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='location_images')),
                ('qr', models.ImageField(upload_to='location_qr')),
            ],
        ),
    ]
