# Generated by Django 4.1.5 on 2023-03-13 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sustainable_app', '0004_question'),
        ('sustainable_app', '0005_location'),
    ]

    operations = [
    ]
