# Generated by Django 4.1.5 on 2023-03-13 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sustainable_app', '0004_question'),
        ('sustainable_app', '0006_dailydata_alter_goal_id_alter_item_id_and_more copy'),
    ]

    operations = [
    ]
