# Generated by Django 4.1.5 on 2023-02-24 11:20

from django.db import migrations

goals = [("Workout", "", 0, 0), ("Drink Water", "", 0, 0),
         ("Recycle Something", "", 0, 0), ("Do Some Work", "", 0, 0),
         ("Eat Something Healthy", "", 0, 0)]


def make_goals(apps, schema_editor):
    Goal = apps.get_model('sustainable_app', 'Goal')

    # Add all items to database
    for values in goals:
        for [name, xp, points] in values:
            goal = Goal(type=Goal.PERSONAL, name=name, point_reward=points, xp_reward=xp)
            goal.save()


def undo_make_goals(apps, schema_editor):
    Goal = apps.get_model('sustainable_app', 'Goal')
    for values in goals:
        for [name, xp, points] in values:
            try:
                goal = Goal.objects.get(
                    type=Goal.PERSONAL, name=name, point_reward=points, xp_reward=xp)
                goal.delete()
            except Goal.DoesNotExist:
                pass


class Migration(migrations.Migration):

    dependencies = [
        ('sustainable_app', '0006_dailydata_alter_goal_id_alter_item_id_and_more copy'),
    ]

    operations = [
        migrations.RunPython(make_goals, undo_make_goals)
    ]
