# Generated by Django 4.1.5 on 2023-02-24 11:20

from django.db import migrations

goals = [("Workout", "", 0, 0), ("Re-use Water Bottle", "", 0, 0),
         ("Recycle Something", "", 0, 0), ("Do Some Work", "", 0, 0),
         ("Eat Something Healthy", "", 0, 0)]


def make_goals(apps, schema_editor):
    """
    Creates goals and add them to database
    """
    Goal = apps.get_model('sustainable_app', 'Goal')

    # Add all items to database
    for [name, desc, xp, points] in goals:
        goal = Goal(type="personal", name=name, description=desc, point_reward=points, xp_reward=xp)
        goal.save()


def undo_make_goals(apps, schema_editor):
    """
    Reverse function to remove goals from database for undoing migration
    """
    Goal = apps.get_model('sustainable_app', 'Goal')
    for [name, desc, xp, points] in goals:
            try:
                goal = Goal.objects.get(
                    type="personal", name=name, description=desc, point_reward=points, xp_reward=xp)
                goal.delete()
            except Goal.DoesNotExist:
                pass


class Migration(migrations.Migration):

    dependencies = [
        ('sustainable_app', '0007_dailydata_item_unlock_level_alter_goal_id_and_more'),
    ]

    operations = [
        migrations.RunPython(make_goals, undo_make_goals)
    ]
