# Generated by Django 4.1.5 on 2023-03-11 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sustainable_app', '0007_dailydata_alter_location_image_personalgoalstatus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailygoalstatus',
            name='point_reward',
        ),
        migrations.RemoveField(
            model_name='dailygoalstatus',
            name='xp_reward',
        ),
    ]
