# Generated by Django 4.1.5 on 2023-03-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sustainable_app', '0008_remove_dailygoalstatus_point_reward_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
