# Generated by Django 4.1.5 on 2023-03-13 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sustainable_app', '0008_create_personal_goals'),
        ('sustainable_app', '0008_survey_rename_question_quizquestion_and_more'),
    ]

    operations = [
    ]
