# Generated by Django 4.1.5 on 2023-03-18 21:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sustainable_app', '0009_merge_migrations'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_last_task_completed',
            field=models.DateField(default=datetime.date(2023, 3, 18)),
        ),
        migrations.AddField(
            model_name='user',
            name='streak_length',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
