# Generated by Django 4.1.5 on 2023-03-18 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sustainable_app', '0009_merge_migrations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailydata',
            name='personal_goals',
        ),
        migrations.AddField(
            model_name='goal',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='goal',
            name='image',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goal',
            name='url',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='PersonalGoalStatus',
        ),
    ]
