# Generated by Django 4.1.5 on 2023-03-11 14:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sustainable_app', '0009_alter_goal_id_alter_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailydata',
            name='date',
            field=models.DateField(default=datetime.date.today, primary_key=True, serialize=False),
        ),
    ]
