# Generated by Django 4.1.5 on 2023-03-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sustainable_app', '0010_statistics_alter_quizquestion_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
