# Generated by Django 4.1.5 on 2023-03-17 13:26

from django.db import migrations, models

def create(apps, schema_editor):
    statistic = apps.get_model('sustainable_app', 'Statistics')
    water = statistic(name='water', quantity=0)
    plastic = statistic(name='plastic', quantity=0)
    water.save()
    plastic.save()

def undo_create(apps, schema_aditor):
    stat = apps.get_model('sustainable_app', 'Statistics')
    try:
        water = stat.objects.get(name="water")
        plastic = stat.objects.get(name="plastic")
        water.delete()
        plastic.delete()
    except stat.DoesNotExist:
        pass

class Migration(migrations.Migration):

    dependencies = [
        ('sustainable_app', '0011_alter_statistics_name_alter_statistics_quantity'),
    ]

    operations = [
        migrations.RunPython(create, undo_create),
    ]
