# Generated by Django 4.1.5 on 2023-03-19 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sustainable_app', '0012_create_statistics'),
        ('sustainable_app', '0012_user_date_last_task_completed_user_streak_length_and_more'),
    ]

    operations = [
    ]
