# Generated by Django 4.1.5 on 2023-03-19 11:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sustainable_app', '0013_merge_20230319_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='type',
            field=models.CharField(choices=[('minigame', 'Minigame'), ('location', 'Location'), ('quiz', 'Quiz'), ('poll', 'Poll'), ('personal', 'Personal')], max_length=8),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_last_task_completed',
            field=models.DateField(default=datetime.datetime(2023, 3, 18, 11, 41, 5, 85092)),
        ),
    ]
