# Generated by Django 4.1.5 on 2023-03-20 15:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sustainable_app', '0014_alter_goal_type_alter_user_date_last_task_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_last_task_completed',
            field=models.DateField(default=datetime.datetime(2023, 3, 19, 15, 56, 27, 190713)),
        ),
    ]
