# Generated by Django 4.1.5 on 2023-03-19 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sustainable_app', '0014_alter_goal_type_alter_user_date_last_task_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surveyquestion',
            old_name='Survey',
            new_name='survey',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='currentlyActive',
        ),
    ]
