# Generated by Django 4.1.5 on 2023-03-19 11:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sustainable_app', '0015_alter_user_date_last_task_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_last_task_completed',
            field=models.DateField(default=datetime.datetime(2023, 3, 18, 11, 52, 55, 605352)),
        ),
    ]
